version: '3.5'
services:
  zabbix-proxy:
    image: zabbix/zabbix-proxy-sqlite3:alpine-latest
    ports:
      - "10051:10051"
    networks:
      - portainer_default
    container_name: zabbix-proxy
    restart: always
    environment:
      ZBX_HOSTNAME: proxy-eosbot
      ZBX_PROXYMODE: '1'
      ZBX_SERVER_HOST: 93.127.211.7
      ZBX_TLSCONNECT: unencrypted
      ZBX_TLSACCEPT: unencrypted
      ZBX_TIMEOUT: 30
      ZBX_CACHESIZE: 512M
      ZBX_STARTDBSYNCERS: 8
      ZBX_HISTORYCACHESIZE: 32M
      ZBX_HISTORYINDEXCACHESIZE: 32M
      ZBX_PROXYLOCALBUFFER: 24
      ZBX_PROXYOFFLINEBUFFER: 24
      ZBX_PROXYHEARTBEATFREQUENCY: 60
      ZBX_CONFIGFREQUENCY: 600
      ZBX_ENABLEREMOTECOMMANDS: 1
      ZBX_DATASENDERFREQUENCY: 30
      ZBX_STARTPOLLERS: 15
      ZBX_STARTPOLLERSUNREACHABLE: 10
      ZBX_STARTPREPROCESSORS: 10
      ZBX_STARTHTTPPOLLERS: 15
      ZBX_STARTTRAPPERS: 20
      ZBX_STARTPINGERS: 15
      ZBX_STARTDISCOVERERS: 5

  zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent2:alpine-latest
    privileged: true
    networks:
      - portainer_default
    ports:
      - 10050:10050
    environment:
      ZBX_HOSTNAME: proxy-eosbot
      ZBX_SERVER_HOST: zabbix-proxy
      ZBX_ENABLEREMOTECOMMANDS: 1
      ZBX_UNSAFEUSERPARAMETERS: 1
      ZBX_ALLOWKEY: system.run[*]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/agent-config/:/etc/zabbix/zabbix_agentd.d/
    user: 0:0
    restart: unless-stopped

networks:
  portainer_default:
    external: true
