##############
# Crie o banco de dados no postgres: createdb -U postgres chatwoot
# Execute o comando para migrar o banco:
#
# bundle exec rails db:chatwoot_prepare
#
#############
version: '3.7'

services:
  chatwoot_app:
    image: 'sendingtk/chatwoot:v3.7.0'
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    entrypoint: docker/entrypoints/rails.sh
    volumes:
      - 'chatwoot_data:/app/storage'
      - 'chatwoot_public:/app'
    networks:
      - traefik
    environment:
      - INSTALLATION_NAME=chatwoot
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
      - SECRET_KEY_BASE=d2vWqo6ZMNi5r9rWgaFdXmPPVhh6jdYfXgyACG1P1A8gAFjGgW
      - FRONTEND_URL=https://chatwoot.eosbotdev.online
      - DEFAULT_LOCALE=pt_BR
      - FORCE_SSL=true
      - ENABLE_ACCOUNT_SIGNUP=false
      - REDIS_URL=redis://redis:6379
      - POSTGRES_HOST=postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=i4PPAa20EqN7
      - POSTGRES_DATABASE=chatwoot
      - ACTIVE_STORAGE_SERVICE=local
      - RAILS_LOG_TO_STDOUT=true
      - USE_INBOX_AVATAR_FOR_BOT=true
      - MAILER_SENDER_EMAIL=suporte@eosbot.com.br
      - SMTP_DOMAIN=hostinger.com
      - SMTP_ADDRESS=smtp.hostinger.com
      - SMTP_PORT=465
      - SMTP_USERNAME=suporte@eosbot.com.br
      - SMTP_PASSWORD=Xv34h32m@
      - SMTP_AUTHENTICATION=login
      - SMTP_ENABLE_STARTTLS_AUTO=true
      - SMTP_OPENSSL_VERIFY_MODE=peer
      - MAILER_INBOUND_EMAIL_DOMAIN=suporte@eosbot.com.br
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 2048M
    labels:
      - traefik.enable=true
      - traefik.http.routers.chatwoot_app.rule=Host(`chat.eosbotdev.online`)
      - traefik.http.routers.chatwoot_app.entrypoints=websecure
      - traefik.http.routers.chatwoot_app.tls.certresolver=cloudflare
      - traefik.http.routers.chatwoot_app.priority=3
      - traefik.http.routers.chatwoot_app.service=chatwoot_app
      - traefik.http.services.chatwoot_app.loadbalancer.server.port=3000 
      - traefik.http.services.chatwoot_app.loadbalancer.passhostheader=true 
      - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.routers.chatwoot_app.middlewares=sslheader@docker

  chatwoot_sidekiq:
    image: 'sendingtk/chatwoot:v3.7.0'
    container_name: chatwoot_sidekiq
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - 'chatwoot_data:/app/storage'
      - 'chatwoot_public:/app'
    networks:
      - traefik
    environment:
      - INSTALLATION_NAME=chatwoot
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
      - SECRET_KEY_BASE=d2vWqo6ZMNi5r9rWgaFdXmPPVhh6jdYfXgyACG1P1A8gAFjGgW
      - FRONTEND_URL=https://chat.eosbotdev.online
      - DEFAULT_LOCALE=pt_BR
      - FORCE_SSL=true
      - ENABLE_ACCOUNT_SIGNUP=false
      - REDIS_URL=redis://redis:6379
      - POSTGRES_HOST=postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=i4PPAa20EqN7
      - POSTGRES_DATABASE=chatwoot
      - ACTIVE_STORAGE_SERVICE=local
      - RAILS_LOG_TO_STDOUT=true
      - USE_INBOX_AVATAR_FOR_BOT=true
      - MAILER_SENDER_EMAIL=suporte@eosbot.com.br
      - SMTP_DOMAIN=hostinger.com
      - SMTP_ADDRESS=smtp.hostinger.com
      - SMTP_PORT=465
      - SMTP_USERNAME=suporte@eosbot.com.br
      - SMTP_PASSWORD=Xv34h32m@
      - SMTP_AUTHENTICATION=login
      - SMTP_ENABLE_STARTTLS_AUTO=true
      - SMTP_OPENSSL_VERIFY_MODE=peer
      - MAILER_INBOUND_EMAIL_DOMAIN=suporte@eosbot.com.br
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 2048M

volumes:
  chatwoot_data:
    external: true
    name: chatwoot_data
  chatwoot_public:
    external: true
    name: chatwoot_public

networks:
  traefik:
    external: true
    name: traefik
