version: "3.7"
services:
  postgrespgvector:              
    image: pgvector/pgvector:pg16                                                                                                                                                              
    volumes:                                                                                                                                                                                   
      - woofed-crm-pg-volume:/var/lib/postgresql/data                                                                                                                                              
    environment:                                                                                                                                                                                  
      POSTGRES_PASSWORD: i4PPAa20EqN7    
    networks:
      - traefik
    ports:                                                                                                                                                                                     
      - "5436:5432"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M

volumes:
  woofed-crm-pg-volume:
    external: true
    name: woofed-crm-pg-volume
networks:
  traefik:
    name: traefik
    external: true