version: "3.7"
services:
  postgrespgvector:
    image: astraonline/postgrespgvector:2024
    container_name: postgrespgvector
    environment:
      - POSTGRES_PASSWORD=i4PPAa20EqN7
    networks:
      - traefik
    ports:
      - "5436:5432"
    volumes:
      - postgrespgvector:/var/lib/postgresql/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M

volumes:
  postgrespgvector:
    external: true
    name: postgrespgvector

networks:
  traefik:
    name: traefik
    external: true