version: "3.7"
services:
  postgres:
    image: "postgres:14"
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=i4PPAa20EqN7
    networks:
      - traefik
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M
      
volumes:
  postgres_data:
    external: true
    name: postgres_data
    
networks:
  traefik:
    external: true
    name: traefik
